User.create(first_name: "lars", last_name: "johnson", username: "lars", email: "lars@lars", password: "lars")
User.create(first_name: "jacob", last_name: "crofts", username: "jacob", email: "jacob@jacob", password: "jacob")
User.create(first_name: "ronny", last_name: "Ewanek", username: "ronny", email: "ronny@ronny", password: "ronny")
User.create(first_name: "kevin", last_name: "corso", username: "kevin", email: "kevin@kevin", password: "kevin")
User.create(first_name: "sue", last_name: "sueson", username: "sue", email: "sue@sue", password: "sue")
User.create(first_name: "jill", last_name: "jilsen", username: "jill", email: "jill@jill", password: "jill")
